dist: trusty
sudo: false
language: java
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
cache:
  directories:
  - ".gradle"
  - "$HOME/.gradle"
  - "$HOME/.m2"
branches:
  only: master
